name: server
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update && apt-get install rsync -y && apt-get install openssh-server -y
      - run: mkdir -p ~/.ssh
      - run: echo "$TEST_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - run: chmod 700 ~/.ssh/id_rsa
      - run: echo "$TEST_ENV" > .env
      - run: npm install
      - run: npm run build
      - run: rsync --progress -avzh -e "ssh " --rsync-path="sudo rsync" --exclude='.git' . ubuntu@124.155.223.181:/var/www/tamado-api
      - run: ssh ubuntu@124.155.223.181 "cd /var/www/tamado-api && pm2 restart all"
